version: '3'
services:
#  chrome:
#    image: selenoid/vnc:chrome_74.0
#    ports:
#      - "4443:4444"
#    volumes:
#      - /dev/shm:/dev/shm
#    networks:
#      - codesel-network


  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
      - "$PWD:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "m-screenshot-based-test_codesel-network"]
    ports:
      - "4444:4444"
    networks:
      - codesel-network
#    depends_on:
#      - chrome
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - codesel-network

  codecept:
    build:
      context: .
      dockerfile: CodeceptDockerfile
    image: mgerasimchuk/codecept
    volumes:
      - ./tests:/project/tests
#    depends_on:
#      - selenoid
    networks:
      - codesel-network

networks:
  codesel-network:
    driver: bridge
